# For more info on HTTP files go to https://aka.ms/vs/httpfile
@GatewayBaseAddress = https://localhost:7164
@Token = eyJhbGciOiJSUzI1NiIsImtpZCI6IkFGRjE3QkM2RUYwQjFCMDJCQ0QzQ0ZFNDg0QTdENEYwQjg4MzU2Q0IiLCJ0eXAiOiJhdCtqd3QiLCJ4NXQiOiJyX0Y3eHU4TEd3SzgwOF9raEtmVThMaURWc3MifQ.eyJuYmYiOjE2OTkyODUyODEsImV4cCI6MTY5OTI4NjE4MSwiaXNzIjoiaHR0cHM6Ly9sb2dpbi5kZXYuZ3JlZW5tb3Rpb24udGVjaCIsImF1ZCI6IkNoYXJnaW5nTmV0d29ya01hbmFnZXIuQXBpIiwiY2xpZW50X2lkIjoiQ2hhcmdpbmdOZXR3b3JrTWFuYWdlci5BcGkuU3dhZ2dlciIsInN1YiI6ImQ3YWFmZDUwLWQwMTUtNDc5My04YjZjLTE3NmYwN2YyODljYyIsImF1dGhfdGltZSI6MTY5ODY3NTM0OCwiaWRwIjoibG9jYWwiLCJzY29wZSI6WyJvcGVuaWQiLCJwcm9maWxlIiwiZW1haWwiLCJDaGFyZ2luZ05ldHdvcmtNYW5hZ2VyLkFwaSJdLCJhbXIiOlsibWZhIl19.johyFCbjR9XPnDnXmKduzBDCF87_mp0QKqGlbxOICcMsfsizDRz7_3tar8FgZ2tfMcZStjRtgpOAg7by3jBYvEatVCev9wK-qZ98ph7qZCTFBwb0YiXP5QE1sFqBAVhzODA3BxUxdg-7wF7Xq7iZnW22NhYXor_7h1qt4PWo7UgZPtn_rptR5wyLr5gCrgkJ1ijx15WegXbiU8Ds289kIJo3ZKRL4KrutvVJHC34zhqR-E3GVB_MtvYEnKtOF71VDyU45lB0O6tqqkcVHmoeZn9lS_ohPdb2c6NYZ395zEs8BxtnIyeE-rqBVutz7eCUDdUM6wDF6QT67SZZo_Xnqw

### An endpoint without permission
Get {{GatewayBaseAddress}}/get-personal-data
Authorization: Bearer {{Token}}

### An endpoint with NoPermissionRequired permission
Get {{GatewayBaseAddress}}/get-no-permission
Authorization: Bearer {{Token}}

### An endpoint with HasDriverPermission permission
Get {{GatewayBaseAddress}}/has-driver-permission
Authorization: Bearer {{Token}}

### An endpoint with CanGetContracts permission that user "has"
Get {{GatewayBaseAddress}}/get-contracts
Authorization: Bearer {{Token}}

### An endpoint with CanKnowFuture permission that user doesn't have
Get {{GatewayBaseAddress}}/get-future-prediction
Authorization: Bearer {{Token}}